#include "openings.hpp"

#include <fstream>

#include "chess_rules.hpp"
#include "util.hpp"

namespace fcd {

namespace {
std::string pgn_tag(const char* name, const std::string& value) {
    std::string escaped;
    for (const char c : value) {
        if (c == '"' || c == '\\') escaped += '\\';
        escaped += c;
    }
    return std::string("[") + name + " \"" + escaped + "\"]\n";
}
}  // namespace

OpeningBook OpeningBook::load_tsv(const std::string& path) {
    std::ifstream in(utf8_path(path), std::ios::binary);
    if (!in) throw Error(FCD_ERR_IO, "cannot open openings file: " + path);

    OpeningBook book;
    std::string line;
    size_t line_number = 0;
    while (std::getline(in, line)) {
        ++line_number;
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line_number == 1) {
            if (line.size() >= 3 && line.compare(0, 3, "\xEF\xBB\xBF") == 0) line.erase(0, 3);
            if (line != "eco\tname\tpgn\tuci\tepd")
                throw Error(FCD_ERR_PARSE, "unexpected header in " + path + " (expected eco, name, pgn, uci, epd)");
            continue;
        }
        if (line.empty()) continue;
        const auto f = split(line, '\t');
        const auto where = path + ":" + std::to_string(line_number);
        if (f.size() != 5) throw Error(FCD_ERR_PARSE, "expected 5 fields at " + where);
        for (const auto& field : f)
            if (field.empty()) throw Error(FCD_ERR_PARSE, "empty field at " + where);

        OpeningEntry e{f[0], f[1], f[2], f[3], f[4]};
        const auto uci = split(e.uci, ' ');
        std::vector<std::string> epds;
        try {
            epds = epds_after_each_ply(uci);
        } catch (const Error& err) {
            throw Error(FCD_ERR_PARSE, std::string(err.what()) + " at " + where);
        }
        if (epds.empty() || epds.back() != e.epd) throw Error(FCD_ERR_PARSE, "UCI line does not reach EPD at " + where);
        if (book.by_epd_.count(e.epd)) throw Error(FCD_ERR_PARSE, "duplicate EPD at " + where);
        book.by_epd_.emplace(e.epd, book.entries_.size());
        book.entries_.push_back(std::move(e));
    }
    if (book.entries_.empty()) throw Error(FCD_ERR_PARSE, "no openings in " + path);
    return book;
}

std::optional<OpeningMatch> OpeningBook::classify(const std::vector<std::string>& uci) const {
    std::optional<OpeningMatch> last;
    const auto epds = epds_after_each_ply(uci);
    for (size_t i = 0; i < epds.size(); ++i) {
        const auto it = by_epd_.find(epds[i]);
        if (it != by_epd_.end()) last = OpeningMatch{&entries_[it->second], static_cast<int>(i + 1)};
    }
    return last;
}

std::pair<std::string, std::string> OpeningBook::split_name(const std::string& name) {
    const auto colon = name.find(':');
    if (colon == std::string::npos) return {trim(name), std::string()};
    return {trim(name.substr(0, colon)), trim(name.substr(colon + 1))};
}

void OpeningBook::write_eco_pgn(const std::string& path) const {
    std::ofstream out(utf8_path(path), std::ios::binary | std::ios::trunc);
    if (!out) throw Error(FCD_ERR_IO, "cannot write ECO file: " + path);
    out << "% ECO classification generated by fastchess-desktop from the Lichess chess-openings TSV.\n\n";
    for (const auto& e : entries_) {
        const auto [family, rest] = split_name(e.name);
        out << pgn_tag("ECO", e.eco) << pgn_tag("Opening", family);
        if (!rest.empty()) {
            const auto comma = rest.find(", ");
            if (comma == std::string::npos) {
                out << pgn_tag("Variation", rest);
            } else {
                out << pgn_tag("Variation", rest.substr(0, comma));
                out << pgn_tag("SubVariation", rest.substr(comma + 2));
            }
        }
        out << '\n' << e.pgn << " *\n\n";
    }
    if (!out) throw Error(FCD_ERR_IO, "write failed: " + path);
}

}  // namespace fcd
